In [1]:
from game import Game
import numpy as np
from main import RandomPlayer
from my_players import HumanPlayer, MinimaxPlayer, ReinforcementPlayer
from collections import defaultdict
from utils import Utils


In [3]:
game = Game()
board = game._board
old_hash = board.astype(np.int8).flatten().tobytes()
print(old_hash)
print(board)

b'\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff'
[[-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]]


In [5]:
stringa_di_test = "000"
print(stringa_di_test.tobytes())

AttributeError: 'str' object has no attribute 'tobytes'

In [6]:
import numpy as np
from hashing_functions import my_hash, my_undo_hash

In [7]:
# Esempio di utilizzo
board = np.array([[1, 1, 1, 1, 1],
                  [1, 1, 1, 1, 1],
                  [1, 1, 1, 1, 1],
                  [1, 1, 1, 1, 1],
                  [1, 1, 1, 1, 1]])

compact_hash = my_hash(board)
print(compact_hash)

board_reconstructed = my_undo_hash(compact_hash)
print(board_reconstructed)

750599937895082
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [32]:
my_dict = defaultdict(int)

In [35]:
my_dict[compact_hash] += 1

In [36]:
value = my_dict[compact_hash]
print(value)

3


In [2]:
reinforcement_player = ReinforcementPlayer()
reinforcement_player.set_random_move(0.9)
random_player = RandomPlayer()
environment = Utils()

In [5]:
len(reinforcement_player.value_dictionary)

133009

In [8]:
reinforcement_player.load_policy("test_size_policy_1")

In [7]:
reinforcement_player.set_random_move(0.9)

In [4]:
environment.train(reinforcement_player, random_player, 10_000, 100, -100, policy_name="test_size_policy")

100%|██████████| 10000/10000 [03:35<00:00, 46.32it/s]


In [5]:
import gzip
import pickle
import msgpack

In [3]:
def create_policy_new(self, policy_file):
    """Creates the policy file with MessagePack"""
    with open(policy_file, 'wb') as fw:
        packed_data = msgpack.packb(self.value_dictionary)
        fw.write(packed_data)

def load_policy_new(self, policy_file):
    """Loads the policy file with MessagePack"""
    with open(policy_file, 'rb') as fr:
        packed_data = fr.read()
        self.value_dictionary = msgpack.unpackb(packed_data)

In [2]:
def create_policy_old(self, policy_file):
    """Creates the policy file"""
    fw = open(policy_file, 'wb')
    pickle.dump(self.value_dictionary, fw)
    fw.close()

def load_policy_old(self, policy_file):
    """Loads the policy file"""
    fr = open(policy_file, 'rb')
    self.value_dictionary = pickle.load(fr)
    fr.close()

In [9]:
reinforcement_player = ReinforcementPlayer()

In [6]:
load_policy_old(reinforcement_player, "policies/old_version_policies/policy_0")

In [4]:
print(len(reinforcement_player.value_dictionary))

NameError: name 'reinforcement_player' is not defined

In [8]:
reinforcement_player.create_policy("policies/good_policy_gzipped")

In [10]:
reinforcement_player.load_policy("policies/good_policy_gzipped")

In [13]:
def create_policy_new_new(self, policy_file):
    """Creates the policy file with MessagePack and gzip compression"""
    with gzip.open(policy_file, 'wb') as fw:
        packed_data = msgpack.packb(self.value_dictionary)
        fw.write(packed_data)

In [14]:
create_policy_new_new(reinforcement_player, "policy_with_gzip_msgpack")

In [10]:
reinforcement_player = ReinforcementPlayer()

In [6]:
load_policy_old(reinforcement_player, "policies/policy_0")

In [9]:
create_policy_new(reinforcement_player, "policy_with_msgpack")
reinforcement_player.create_policy("policy_with_pickle")

In [11]:
reinforcement_player.load_policy("policy_with_pickle")

In [16]:
reinforcement_player.create_policy("old_size_policy")
create_policy_new(reinforcement_player, "new_size_policy")

In [13]:
create_policy_new(reinforcement_player, "test_size_policy")

In [17]:
new_reinforcement_player = ReinforcementPlayer()
load_policy_new(new_reinforcement_player, "test_size_policy")

In [18]:
len(new_reinforcement_player.value_dictionary)

261379

In [1]:
from hashing_functions import my_hash, my_undo_hash

In [5]:
reinforcement_player = ReinforcementPlayer()

NameError: name 'ReinforcementPlayer' is not defined

In [3]:
len(reinforcement_player.value_dictionary)

NameError: name 'reinforcement_player' is not defined