In [1]:
from game import Game
import numpy as np
from main import RandomPlayer
from my_players import HumanPlayer, MinimaxPlayer


In [10]:
game = Game()
original_board = game._board
hashed_board = original_board.flatten().tobytes()
print("original:\t", hashed_board)
print("length:\t", len(hashed_board))
hashed_board = original_board.astype(np.int8).flatten().tobytes()
print("new:\t\t", hashed_board)
print("length:\t", len(hashed_board))


original:	 b'\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff'
length:	 50
new:		 b'\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff'
length:	 25


In [30]:
# hashed_board = board.flatten().tobytes()
hashed_board = board.astype(np.int8).flatten().tobytes()

print(hashed_board) 

b'\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff'


In [32]:
# La tua stringa di byte
# byte_string = b'\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff'


# Convertire in un array NumPy di tipo 'int8'
array = np.frombuffer(hashed_board, dtype=np.int8)
print(array)

# Ridimensionare l'array se necessario (esempio per una forma 5x5)
reshaped_array = array.reshape(5, 5)

print(reshaped_array)


[-1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1
 -1]
[[-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]]


In [24]:
# original_board = np.frombuffer(hashed_board, dtype=np.int8).reshape((3, 3))
original_board = np.frombuffer(hashed_board, dtype=np.int32).reshape(5, 5)

ValueError: buffer size must be a multiple of element size

In [14]:

# Creazione di un array 5x5 di esempio
array = np.array([[1, 2, 3, 4, 5],
                  [6, 7, 8, 9, 10],
                  [11, 12, 13, 14, 15],
                  [16, 17, 18, 19, 20],
                  [21, 22, 23, 24, 25]])

# Ruotare l'array di 90 gradi in senso antiorario
# rotated_array = np.rot90(array, k=4)

# print(rotated_array)
print(np.rot90(array, k=0))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [12]:
hashed_array = array.flatten().tobytes()
print(hashed_array)

b'\x01\x00\x00\x00\x00\x00\x00\x00\x02\x00\x00\x00\x00\x00\x00\x00\x03\x00\x00\x00\x00\x00\x00\x00\x04\x00\x00\x00\x00\x00\x00\x00\x05\x00\x00\x00\x00\x00\x00\x00\x06\x00\x00\x00\x00\x00\x00\x00\x07\x00\x00\x00\x00\x00\x00\x00\x08\x00\x00\x00\x00\x00\x00\x00\t\x00\x00\x00\x00\x00\x00\x00\n\x00\x00\x00\x00\x00\x00\x00\x0b\x00\x00\x00\x00\x00\x00\x00\x0c\x00\x00\x00\x00\x00\x00\x00\r\x00\x00\x00\x00\x00\x00\x00\x0e\x00\x00\x00\x00\x00\x00\x00\x0f\x00\x00\x00\x00\x00\x00\x00\x10\x00\x00\x00\x00\x00\x00\x00\x11\x00\x00\x00\x00\x00\x00\x00\x12\x00\x00\x00\x00\x00\x00\x00\x13\x00\x00\x00\x00\x00\x00\x00\x14\x00\x00\x00\x00\x00\x00\x00\x15\x00\x00\x00\x00\x00\x00\x00\x16\x00\x00\x00\x00\x00\x00\x00\x17\x00\x00\x00\x00\x00\x00\x00\x18\x00\x00\x00\x00\x00\x00\x00\x19\x00\x00\x00\x00\x00\x00\x00'


In [13]:
original_array = np.frombuffer(hashed_array, dtype=np.int64).reshape(5, 5)
print(original_array)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
